name: Push readme.md to Modrinth
on: [push]
jobs:
  Push-Readme:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source Tree
      uses: actions/checkout@v4

    - name: Push readme.md
      shell: pwsh
      env:
        MODRINTH_API_KEY: ${{ secrets.MODRINTH_API_KEY }}
      run: |
        # Define API Key and URL
        $ModrinthURL = "https://api.modrinth.com/v2/project/keepsomeinventory"
        $apiKey = $env:MODRINTH_API_KEY
        
        # Load README content
        $Readme = Get-Content -Path .\README.md -Raw
        
        # Prepare JSON body
        $JsonBody = @{
            body = $Readme
        } | ConvertTo-Json -Depth 10
        
        # Headers
        $headers = @{
            "Authorization" = "Bearer $apiKey"
            "User-Agent" = "thepwrtank18/keepsomeinventory/1.0 (pt18.relay@gmail.com)"
            "Content-Type" = "application/json"
        }
        
        # Debugging: Output the headers being sent
        Write-Host "Sending request with headers:"
        $headers | ForEach-Object { Write-Host "$($_.Key): $($_.Value)" }
        
        # Send the PATCH request using Invoke-RestMethod
        try {
            $response = Invoke-RestMethod -Uri $ModrinthURL -Method Patch -Headers $headers -Body $JsonBody
        
            # Check the response
            if ($response -eq $null) {
                Write-Host "❌ Failed to get a valid response from Modrinth."
            } else {
                Write-Host "✅ Success: $($response)"
            }
        } catch {
            Write-Host "❌ Error: $($_.Exception.Message)"
        }

