name: Push readme.md to Modrinth
on: [push]
jobs:
  Push-Readme:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source Tree
      uses: actions/checkout@v4
    - name: Push readme.md
      shell: pwsh
      env:
        MODRINTH_API_KEY: ${{ secrets.MODRINTH_API_KEY }}
      run: |
        $Readme = Get-Content -Path .\README.md
        $ModrinthURL = "https://api.modrinth.com/v2/project/keepsomeinventory"
        $UserAgent = "thepwrtank18/keepsomeinventory/1.0 (pt18.relay@gmail.com)"
        $Headers = @{
          Authorization = "Bearer $env:MODRINTH_API_KEY"
        }
        Invoke-WebRequest -Uri $ModrinthURL -Method Patch -UserAgent $UserAgent -Headers $Headers Body $Readme
